name: Build KMP

on:
  push:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Keyman Compiler
        run: npm install -g @keymanapp/kmc

      - name: Verify repo files
        run: |
          echo "=== FILE LIST ==="
          ls -R

      - name: Build keyboard project
        run: |
          kmc build mr-godrej.kps

      - name: Verify build output
        run: ls -R

      - name: Upload KMP package
        uses: actions/upload-artifact@v4
        with:
          name: mr-godrej-keyboard
          path: "*.kmp"
